import { expect, test } from '@playwright/test'

test('public roadmap works without an owner or backend and supports checkpoint history', async ({ page }, info) => {
  const apiRequests: string[] = []
  const errors: string[] = []
  page.on('pageerror', error => errors.push(error.message))
  page.on('request', request => { if (/\/(api\/|health)/.test(new URL(request.url()).pathname)) apiRequests.push(request.url()) })
  await page.route('**/api/**', route => route.abort())
  await page.route('**/health', route => route.abort())
  await page.goto('/dev-roadmap?milestone=contracts')
  await expect(page).toHaveTitle('Development roadmap · Sensei++')
  await expect(page.getByRole('heading', { level: 1 })).toContainText('The making of')
  await expect(page.getByRole('article', { name: 'Make the contract dependable details' })).toBeVisible()
  await page.getByRole('button', { name: /Prepare the next release/ }).click()
  await expect(page).toHaveURL(/milestone=release/)
  await expect(page.getByRole('article', { name: 'Prepare the next release details' })).toContainText('WHAT IT WILL TAKE')
  await page.goBack()
  await expect(page.getByRole('article', { name: 'Make the contract dependable details' })).toBeVisible()
  await page.reload()
  await expect(page.getByRole('article', { name: 'Make the contract dependable details' })).toBeVisible()
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBe(true)
  expect(await page.evaluate(() => localStorage.getItem('sensei.owner-id'))).toBeNull()
  expect(apiRequests).toEqual([])
  expect(errors).toEqual([])
  await page.screenshot({ path: `test-results/ui/roadmap-${info.project.name}.png`, fullPage: true })
  await page.goto('/')
  await page.getByRole('link', { name: 'Build journal' }).click()
  await expect(page).toHaveURL(/\/dev-roadmap$/)
  await expect(page).toHaveTitle('Development roadmap · Sensei++')
})

test('journal combines search and categories, resets empty results and opens accessible source records', async ({ page }) => {
  await page.goto('/dev-roadmap')
  await page.getByRole('button', { name: 'Verification', exact: true }).click()
  await page.getByRole('searchbox', { name: 'Search development log' }).fill('rollback')
  await expect(page.locator('.rd-log-entry')).toHaveCount(1)
  await expect(page.getByRole('status')).toContainText('1 entry')
  await page.locator('.rd-log-entry summary').click()
  const sourceButton = page.getByRole('button', { name: 'Source record', exact: true })
  await sourceButton.click()
  const dialog = page.getByRole('dialog')
  await expect(dialog).toBeVisible()
  await expect(dialog.getByLabel('Source document')).toContainText('# Phase 1 learning implementation')
  await page.keyboard.press('Escape')
  await expect(dialog).toBeHidden()
  await expect(sourceButton).toBeFocused()
  await page.getByRole('searchbox').fill('there-is-no-such-note')
  await expect(page.getByRole('heading', { name: 'No notes on that page.' })).toBeVisible()
  await page.getByRole('button', { name: 'Reset filters' }).click()
  await expect(page.locator('.rd-log-entry')).toHaveCount(12)
  await page.getByRole('button', { name: 'Design', exact: true }).click()
  await expect(page.locator('.rd-log-entry')).toHaveCount(2)
  await page.locator('.rd-log-entry').first().locator('summary').click()
  await page.getByRole('button', { name: 'View checkpoint' }).click()
  await expect(page).toHaveURL(/milestone=workbench/)
  await expect(page.getByRole('article', { name: 'Give the work a home details' })).toBeFocused()
  await page.getByText('Evidence & delivery notes', { exact: true }).click()
  await page.getByRole('button', { name: 'Read the source record' }).click()
  await expect(page.getByLabel('Source document')).toContainText('# Sensei++ SPA design implementation')
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBe(true)
})

test('milestones and future phases work by keyboard with reduced motion and enlarged text', async ({ page }) => {
  await page.emulateMedia({ reducedMotion: 'reduce' })
  await page.goto('/dev-roadmap?milestone=missing')
  const checkpoint = page.getByRole('button', { name: /Lay the groundwork/ })
  await checkpoint.focus()
  await page.keyboard.press('Enter')
  await expect(checkpoint).toHaveAttribute('aria-pressed', 'true')
  await expect(page.getByRole('article', { name: 'Lay the groundwork details' })).toBeVisible()
  await page.locator('.rd-horizon summary').focus()
  await page.keyboard.press('Enter')
  await expect(page.getByRole('heading', { name: 'Take it with you' })).toBeVisible()
  await page.getByRole('button', { name: 'Read the delivery plan' }).click()
  await expect(page.getByLabel('Source document')).toContainText('# Learning delivery plan')
  await page.keyboard.press('Escape')
  await page.evaluate(() => { document.documentElement.style.fontSize = '200%' })
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBe(true)
  expect(await page.locator('.rd-cover').evaluate(element => getComputedStyle(element).animationName)).toBe('none')
})
