<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <FrameworkReference Include="Microsoft.AspNetCore.App" />
    <ProjectReference Include="..\Sensei.Modules.Learning.Application\Sensei.Modules.Learning.Application.csproj" />
    <ProjectReference Include="..\Sensei.Modules.Learning.Domain\Sensei.Modules.Learning.Domain.csproj" />
    <ProjectReference Include="..\..\..\BuildingBlocks\Sensei.BuildingBlocks.Persistence\Sensei.BuildingBlocks.Persistence.csproj" />
  </ItemGroup>

</Project>
