// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Sensei.BuildingBlocks.Persistence;

#nullable disable

namespace Sensei.Host.Persistence.Migrations
{
    [DbContext(typeof(SenseiDbContext))]
    [Migration("20260928195533_LearningFoundation")]
    partial class LearningFoundation
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.20")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Sensei.Modules.Evidence.Domain.EvidenceObservation", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Aspect")
                        .IsRequired()
                        .HasMaxLength(240)
                        .HasColumnType("character varying(240)")
                        .HasColumnName("aspect");

                    b.Property<string>("Assistance")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("assistance");

                    b.Property<Guid>("ConceptId")
                        .HasColumnType("uuid")
                        .HasColumnName("concept_id");

                    b.Property<string>("Conditions")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("conditions");

                    b.Property<DateTimeOffset>("ObservedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("observed_at");

                    b.Property<Guid>("OwnerId")
                        .HasColumnType("uuid")
                        .HasColumnName("owner_id");

                    b.Property<string>("SignalKind")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("signal_kind");

                    b.Property<Guid>("SourceId")
                        .HasColumnType("uuid")
                        .HasColumnName("source_id");

                    b.Property<string>("SourceKind")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("source_kind");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("status");

                    b.Property<int>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("integer")
                        .HasColumnName("version");

                    b.HasKey("Id")
                        .HasName("pk_observations");

                    b.HasIndex("ConceptId");

                    b.HasIndex("OwnerId", "ConceptId")
                        .HasDatabaseName("ix_observations_owner_concept");

                    b.HasIndex("OwnerId", "Id")
                        .IsUnique()
                        .HasDatabaseName("ux_observations_owner_id");

                    b.HasIndex("OwnerId", "ObservedAt", "Id")
                        .HasDatabaseName("ix_observations_owner_observed_id");

                    b.ToTable("observations", "evidence", t =>
                        {
                            t.HasCheckConstraint("ck_observations_id_not_empty", "id <> '00000000-0000-0000-0000-000000000000'::uuid");

                            t.HasCheckConstraint("ck_observations_owner_not_empty", "owner_id <> '00000000-0000-0000-0000-000000000000'::uuid");

                            t.HasCheckConstraint("ck_observations_version_positive", "version >= 1");
                        });
                });

            modelBuilder.Entity("Sensei.Modules.Evidence.Domain.EvidenceStatusRevision", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("ObservationId")
                        .HasColumnType("uuid")
                        .HasColumnName("observation_id");

                    b.Property<DateTimeOffset>("ReceivedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("received_at");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("status");

                    b.HasKey("Id");

                    b.HasIndex("ObservationId");

                    b.ToTable("status_revisions", "evidence");
                });

            modelBuilder.Entity("Sensei.Modules.Evidence.Domain.KnowledgeContribution", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<bool>("Admitted")
                        .HasColumnType("boolean")
                        .HasColumnName("admitted");

                    b.Property<bool>("AnswerAware")
                        .HasColumnType("boolean")
                        .HasColumnName("answer_aware");

                    b.Property<bool>("Assisted")
                        .HasColumnType("boolean")
                        .HasColumnName("assisted");

                    b.Property<Guid>("AttemptId")
                        .HasColumnType("uuid")
                        .HasColumnName("attempt_id");

                    b.Property<Guid>("ConceptId")
                        .HasColumnType("uuid")
                        .HasColumnName("concept_id");

                    b.Property<Guid>("FamilyId")
                        .HasColumnType("uuid")
                        .HasColumnName("family_id");

                    b.Property<Guid>("ObservationId")
                        .HasColumnType("uuid")
                        .HasColumnName("observation_id");

                    b.Property<Guid>("OwnerId")
                        .HasColumnType("uuid")
                        .HasColumnName("owner_id");

                    b.Property<string>("PolicyVersion")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("policy_version");

                    b.Property<DateTimeOffset>("ReceivedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("received_at");

                    b.Property<Guid>("ResultId")
                        .HasColumnType("uuid")
                        .HasColumnName("result_id");

                    b.Property<int?>("Score")
                        .HasColumnType("integer")
                        .HasColumnName("score");

                    b.Property<string>("SelfReview")
                        .HasColumnType("text")
                        .HasColumnName("self_review");

                    b.Property<Guid>("SessionId")
                        .HasColumnType("uuid")
                        .HasColumnName("session_id");

                    b.HasKey("Id");

                    b.HasIndex("ConceptId");

                    b.HasIndex("FamilyId");

                    b.HasIndex("ObservationId");

                    b.HasIndex("OwnerId", "AttemptId");

                    b.HasIndex("OwnerId", "ResultId");

                    b.HasIndex("OwnerId", "SessionId");

                    b.HasIndex("ResultId", "ConceptId")
                        .IsUnique();

                    b.ToTable("knowledge_contributions", "evidence");
                });

            modelBuilder.Entity("Sensei.Modules.Evidence.Domain.KnowledgeState", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("ConceptId")
                        .HasColumnType("uuid")
                        .HasColumnName("concept_id");

                    b.Property<double?>("Estimate")
                        .HasColumnType("double precision")
                        .HasColumnName("estimate");

                    b.Property<Guid>("OwnerId")
                        .HasColumnType("uuid")
                        .HasColumnName("owner_id");

                    b.Property<string>("PolicyVersion")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("policy_version");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("OwnerId", "ConceptId")
                        .IsUnique();

                    b.ToTable("knowledge_states", "evidence");
                });

            modelBuilder.Entity("Sensei.Modules.Evidence.Domain.SelfReviewAllowance", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("ConceptId")
                        .HasColumnType("uuid")
                        .HasColumnName("concept_id");

                    b.Property<DateTimeOffset>("LastAdmittedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_admitted_at");

                    b.Property<Guid>("OwnerId")
                        .HasColumnType("uuid")
                        .HasColumnName("owner_id");

                    b.HasKey("Id");

                    b.HasIndex("ConceptId");

                    b.HasIndex("OwnerId", "ConceptId")
                        .IsUnique();

                    b.ToTable("self_review_allowances", "evidence");
                });

            modelBuilder.Entity("Sensei.Modules.Experience.Domain.ExperienceEntry", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<bool>("IsArchived")
                        .HasColumnType("boolean")
                        .HasColumnName("is_archived");

                    b.Property<Guid>("OwnerId")
                        .HasColumnType("uuid")
                        .HasColumnName("owner_id");

                    b.Property<int>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("integer")
                        .HasColumnName("version");

                    b.HasKey("Id")
                        .HasName("pk_entries");

                    b.HasIndex("OwnerId", "Id")
                        .IsUnique()
                        .HasDatabaseName("ux_entries_owner_id");

                    b.HasIndex("OwnerId", "CreatedAt", "Id")
                        .HasDatabaseName("ix_entries_owner_created_id");

                    b.ToTable("entries", "experience", t =>
                        {
                            t.HasCheckConstraint("ck_entries_id_not_empty", "id <> '00000000-0000-0000-0000-000000000000'::uuid");

                            t.HasCheckConstraint("ck_entries_owner_not_empty", "owner_id <> '00000000-0000-0000-0000-000000000000'::uuid");

                            t.HasCheckConstraint("ck_entries_version_positive", "version >= 1");
                        });
                });

            modelBuilder.Entity("Sensei.Modules.Experience.Domain.ExperienceRevision", b =>
                {
                    b.Property<Guid>("EntryId")
                        .HasColumnType("uuid")
                        .HasColumnName("entry_id");

                    b.Property<int>("Number")
                        .HasColumnType("integer")
                        .HasColumnName("number");

                    b.Property<string>("Actions")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("actions");

                    b.Property<string>("Alternatives")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("alternatives");

                    b.Property<string>("ApprovalState")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("approval_state");

                    b.Property<DateTimeOffset?>("ApprovedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("approved_at");

                    b.Property<string>("Context")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("context");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("ImpactState")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("impact_state");

                    b.Property<string>("Outcome")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("outcome");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("role");

                    b.Property<string>("Setting")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("setting");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(240)
                        .HasColumnType("character varying(240)")
                        .HasColumnName("title");

                    b.HasKey("EntryId", "Number")
                        .HasName("pk_entry_revisions");

                    b.ToTable("entry_revisions", "experience", t =>
                        {
                            t.HasCheckConstraint("ck_entry_revisions_approval", "approval_state IN ('Draft', 'Approved', 'Retracted')");

                            t.HasCheckConstraint("ck_entry_revisions_impact", "impact_state IN ('Unknown', 'Qualitative', 'Measured')");

                            t.HasCheckConstraint("ck_entry_revisions_number_positive", "number >= 1");

                            t.HasCheckConstraint("ck_entry_revisions_setting", "setting IN ('Employment', 'Coursework', 'PersonalProject', 'Other')");
                        });
                });

            modelBuilder.Entity("Sensei.Modules.Experience.Domain.ExperienceRevisionConcept", b =>
                {
                    b.Property<Guid>("EntryId")
                        .HasColumnType("uuid")
                        .HasColumnName("entry_id");

                    b.Property<int>("RevisionNumber")
                        .HasColumnType("integer")
                        .HasColumnName("revision_number");

                    b.Property<Guid>("ConceptId")
                        .HasColumnType("uuid")
                        .HasColumnName("concept_id");

                    b.HasKey("EntryId", "RevisionNumber", "ConceptId")
                        .HasName("pk_entry_revision_concepts");

                    b.HasIndex("ConceptId")
                        .HasDatabaseName("ix_entry_revision_concepts_concept");

                    b.ToTable("entry_revision_concepts", "experience", t =>
                        {
                            t.HasCheckConstraint("ck_entry_revision_concepts_id_not_empty", "concept_id <> '00000000-0000-0000-0000-000000000000'::uuid");
                        });
                });

            modelBuilder.Entity("Sensei.Modules.Identity.Domain.UserAccount", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("AnswerLanguage")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("answer_language");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("display_name");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(320)
                        .HasColumnType("character varying(320)")
                        .HasColumnName("email");

                    b.Property<string>("TimeZone")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("time_zone");

                    b.Property<string>("UiLocale")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("ui_locale");

                    b.Property<int>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("integer")
                        .HasColumnName("version");

                    b.HasKey("Id")
                        .HasName("pk_users");

                    b.HasIndex("Email")
                        .IsUnique()
                        .HasDatabaseName("ux_users_email");

                    b.HasIndex("CreatedAt", "Id")
                        .HasDatabaseName("ix_users_created_at_id");

                    b.ToTable("users", "identity", t =>
                        {
                            t.HasCheckConstraint("ck_users_id_not_empty", "id <> '00000000-0000-0000-0000-000000000000'::uuid");

                            t.HasCheckConstraint("ck_users_version_positive", "version >= 1");
                        });
                });

            modelBuilder.Entity("Sensei.Modules.Learning.Domain.Concept", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<string>("Difficulty")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("difficulty");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("character varying(160)")
                        .HasColumnName("key");

                    b.Property<string>("Locale")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("locale");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(240)
                        .HasColumnType("character varying(240)")
                        .HasColumnName("name");

                    b.Property<int>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("integer")
                        .HasColumnName("version");

                    b.HasKey("Id")
                        .HasName("pk_concepts");

                    b.HasIndex("Key")
                        .IsUnique()
                        .HasDatabaseName("ux_concepts_key");

                    b.HasIndex("Key", "Id")
                        .HasDatabaseName("ix_concepts_key_id");

                    b.ToTable("concepts", "learning", t =>
                        {
                            t.HasCheckConstraint("ck_concepts_difficulty", "difficulty IN ('Beginner', 'Intermediate', 'Advanced')");

                            t.HasCheckConstraint("ck_concepts_id_not_empty", "id <> '00000000-0000-0000-0000-000000000000'::uuid");

                            t.HasCheckConstraint("ck_concepts_version_positive", "version >= 1");
                        });
                });

            modelBuilder.Entity("Sensei.Modules.Learning.Domain.ConceptRelation", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Kind")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("kind");

                    b.Property<Guid>("SourceId")
                        .HasColumnType("uuid")
                        .HasColumnName("source_id");

                    b.Property<Guid>("TargetId")
                        .HasColumnType("uuid")
                        .HasColumnName("target_id");

                    b.HasKey("Id");

                    b.HasIndex("TargetId");

                    b.HasIndex("SourceId", "TargetId", "Kind")
                        .IsUnique();

                    b.ToTable("concept_relations", "learning");
                });

            modelBuilder.Entity("Sensei.Modules.Learning.Domain.ExerciseConcept", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("ConceptId")
                        .HasColumnType("uuid")
                        .HasColumnName("concept_id");

                    b.Property<Guid>("ExerciseVersionId")
                        .HasColumnType("uuid")
                        .HasColumnName("exercise_version_id");

                    b.HasKey("Id");

                    b.HasIndex("ConceptId");

                    b.HasIndex("ExerciseVersionId", "ConceptId")
                        .IsUnique();

                    b.ToTable("exercise_concepts", "learning");
                });

            modelBuilder.Entity("Sensei.Modules.Learning.Domain.ExerciseFamily", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("key");

                    b.HasKey("Id");

                    b.HasIndex("Key")
                        .IsUnique();

                    b.ToTable("exercise_families", "learning");
                });

            modelBuilder.Entity("Sensei.Modules.Learning.Domain.ExerciseResult", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("AttemptId")
                        .HasColumnType("uuid")
                        .HasColumnName("attempt_id");

                    b.Property<string>("EvaluatorVersion")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("evaluator_version");

                    b.Property<Guid>("OwnerId")
                        .HasColumnType("uuid")
                        .HasColumnName("owner_id");

                    b.Property<int?>("Score")
                        .HasColumnType("integer")
                        .HasColumnName("score");

                    b.Property<string>("SelfReview")
                        .HasColumnType("text")
                        .HasColumnName("self_review");

                    b.HasKey("Id");

                    b.HasIndex("AttemptId")
                        .IsUnique();

                    b.HasIndex("OwnerId", "AttemptId");

                    b.ToTable("results", "learning");
                });

            modelBuilder.Entity("Sensei.Modules.Learning.Domain.ExerciseVersion", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<bool>("Available")
                        .HasColumnType("boolean")
                        .HasColumnName("available");

                    b.Property<int>("EstimatedSeconds")
                        .HasColumnType("integer")
                        .HasColumnName("estimated_seconds");

                    b.Property<string>("EvaluationJson")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("evaluation_json");

                    b.Property<string>("EvaluatorVersion")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("evaluator_version");

                    b.Property<Guid>("ExerciseId")
                        .HasColumnType("uuid")
                        .HasColumnName("exercise_id");

                    b.Property<Guid>("FamilyId")
                        .HasColumnType("uuid")
                        .HasColumnName("family_id");

                    b.Property<string>("HintsJson")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("hints_json");

                    b.Property<string>("InteractionJson")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("interaction_json");

                    b.Property<string>("Locale")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("locale");

                    b.Property<Guid?>("MaterialVersionId")
                        .HasColumnType("uuid")
                        .HasColumnName("material_version_id");

                    b.Property<Guid>("PrimaryConceptId")
                        .HasColumnType("uuid")
                        .HasColumnName("primary_concept_id");

                    b.Property<string>("PromptJson")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("prompt_json");

                    b.Property<int>("Revision")
                        .HasColumnType("integer")
                        .HasColumnName("revision");

                    b.Property<int>("SchemaVersion")
                        .HasColumnType("integer")
                        .HasColumnName("schema_version");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("type");

                    b.HasKey("Id");

                    b.HasIndex("FamilyId");

                    b.HasIndex("MaterialVersionId");

                    b.HasIndex("PrimaryConceptId");

                    b.HasIndex("ExerciseId", "Revision")
                        .IsUnique();

                    b.ToTable("exercise_versions", "learning");
                });

            modelBuilder.Entity("Sensei.Modules.Learning.Domain.GoalConcept", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("ConceptId")
                        .HasColumnType("uuid")
                        .HasColumnName("concept_id");

                    b.Property<Guid>("GoalId")
                        .HasColumnType("uuid")
                        .HasColumnName("goal_id");

                    b.HasKey("Id");

                    b.HasIndex("ConceptId");

                    b.HasIndex("GoalId", "ConceptId")
                        .IsUnique();

                    b.ToTable("goal_concepts", "learning");
                });

            modelBuilder.Entity("Sensei.Modules.Learning.Domain.LearningAttempt", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<bool>("AnswerAware")
                        .HasColumnType("boolean")
                        .HasColumnName("answer_aware");

                    b.Property<string>("AnswerJson")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("answer_json");

                    b.Property<bool>("Assisted")
                        .HasColumnType("boolean")
                        .HasColumnName("assisted");

                    b.Property<Guid>("ExerciseVersionId")
                        .HasColumnType("uuid")
                        .HasColumnName("exercise_version_id");

                    b.Property<Guid>("ItemId")
                        .HasColumnType("uuid")
                        .HasColumnName("item_id");

                    b.Property<string>("Note")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("note");

                    b.Property<Guid>("OwnerId")
                        .HasColumnType("uuid")
                        .HasColumnName("owner_id");

                    b.Property<Guid?>("PreviousAttemptId")
                        .HasColumnType("uuid")
                        .HasColumnName("previous_attempt_id");

                    b.Property<DateTimeOffset>("ReceivedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("received_at");

                    b.Property<Guid>("SessionId")
                        .HasColumnType("uuid")
                        .HasColumnName("session_id");

                    b.HasKey("Id");

                    b.HasIndex("OwnerId", "PreviousAttemptId");

                    b.HasIndex("OwnerId", "SessionId", "ItemId", "ExerciseVersionId");

                    b.ToTable("attempts", "learning");
                });

            modelBuilder.Entity("Sensei.Modules.Learning.Domain.LearningEvent", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid?>("AttemptId")
                        .HasColumnType("uuid")
                        .HasColumnName("attempt_id");

                    b.Property<Guid?>("ExerciseVersionId")
                        .HasColumnType("uuid")
                        .HasColumnName("exercise_version_id");

                    b.Property<Guid?>("ItemId")
                        .HasColumnType("uuid")
                        .HasColumnName("item_id");

                    b.Property<string>("Kind")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("kind");

                    b.Property<Guid?>("MaterialVersionId")
                        .HasColumnType("uuid")
                        .HasColumnName("material_version_id");

                    b.Property<Guid>("OperationId")
                        .HasColumnType("uuid")
                        .HasColumnName("operation_id");

                    b.Property<string>("Origin")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("origin");

                    b.Property<Guid>("OwnerId")
                        .HasColumnType("uuid")
                        .HasColumnName("owner_id");

                    b.Property<DateTimeOffset>("ReceivedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("received_at");

                    b.Property<int>("SchemaVersion")
                        .HasColumnType("integer")
                        .HasColumnName("schema_version");

                    b.Property<Guid?>("SessionId")
                        .HasColumnType("uuid")
                        .HasColumnName("session_id");

                    b.HasKey("Id");

                    b.HasIndex("ExerciseVersionId");

                    b.HasIndex("MaterialVersionId");

                    b.HasIndex("OwnerId", "AttemptId");

                    b.HasIndex("OwnerId", "SessionId");

                    b.HasIndex("OwnerId", "ReceivedAt", "Id");

                    b.ToTable("events", "learning");
                });

            modelBuilder.Entity("Sensei.Modules.Learning.Domain.LearningGoal", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<bool>("Archived")
                        .HasColumnType("boolean")
                        .HasColumnName("archived");

                    b.Property<string>("Intention")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("intention");

                    b.Property<Guid>("OwnerId")
                        .HasColumnType("uuid")
                        .HasColumnName("owner_id");

                    b.Property<Guid?>("RoadmapVersionId")
                        .HasColumnType("uuid")
                        .HasColumnName("roadmap_version_id");

                    b.Property<int>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("integer")
                        .HasColumnName("version");

                    b.HasKey("Id");

                    b.HasIndex("OwnerId");

                    b.HasIndex("RoadmapVersionId");

                    b.ToTable("goals", "learning");
                });

            modelBuilder.Entity("Sensei.Modules.Learning.Domain.LearningSession", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<int>("ActualCount")
                        .HasColumnType("integer")
                        .HasColumnName("actual_count");

                    b.Property<Guid?>("ConceptId")
                        .HasColumnType("uuid")
                        .HasColumnName("concept_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid?>("EnrollmentId")
                        .HasColumnType("uuid")
                        .HasColumnName("enrollment_id");

                    b.Property<string>("FeedbackPolicy")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("feedback_policy");

                    b.Property<Guid>("OwnerId")
                        .HasColumnType("uuid")
                        .HasColumnName("owner_id");

                    b.Property<int>("Position")
                        .HasColumnType("integer")
                        .HasColumnName("position");

                    b.Property<int>("RequestedCount")
                        .HasColumnType("integer")
                        .HasColumnName("requested_count");

                    b.Property<string>("ReturnContext")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("return_context");

                    b.Property<Guid?>("RoadmapStageId")
                        .HasColumnType("uuid")
                        .HasColumnName("roadmap_stage_id");

                    b.Property<string>("SelectionPolicy")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("selection_policy");

                    b.Property<string>("State")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("state");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<int>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("integer")
                        .HasColumnName("version");

                    b.HasKey("Id");

                    b.HasIndex("ConceptId");

                    b.HasIndex("OwnerId")
                        .IsUnique()
                        .HasFilter("state IN ('Active', 'Paused')");

                    b.HasIndex("RoadmapStageId");

                    b.HasIndex("OwnerId", "EnrollmentId");

                    b.ToTable("sessions", "learning");
                });

            modelBuilder.Entity("Sensei.Modules.Learning.Domain.MaterialVersion", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<bool>("Available")
                        .HasColumnType("boolean")
                        .HasColumnName("available");

                    b.Property<string>("BlocksJson")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("blocks_json");

                    b.Property<Guid>("ConceptId")
                        .HasColumnType("uuid")
                        .HasColumnName("concept_id");

                    b.Property<string>("Locale")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("locale");

                    b.Property<int>("SchemaVersion")
                        .HasColumnType("integer")
                        .HasColumnName("schema_version");

                    b.HasKey("Id");

                    b.HasIndex("ConceptId");

                    b.ToTable("material_versions", "learning");
                });

            modelBuilder.Entity("Sensei.Modules.Learning.Domain.OperationReceipt", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Digest")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("digest");

                    b.Property<string>("Kind")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("kind");

                    b.Property<Guid>("OperationId")
                        .HasColumnType("uuid")
                        .HasColumnName("operation_id");

                    b.Property<Guid>("OutcomeId")
                        .HasColumnType("uuid")
                        .HasColumnName("outcome_id");

                    b.Property<Guid>("OwnerId")
                        .HasColumnType("uuid")
                        .HasColumnName("owner_id");

                    b.Property<int>("ResponseVersion")
                        .HasColumnType("integer")
                        .HasColumnName("response_version");

                    b.Property<Guid>("TargetId")
                        .HasColumnType("uuid")
                        .HasColumnName("target_id");

                    b.HasKey("Id");

                    b.HasIndex("OwnerId", "OperationId")
                        .IsUnique();

                    b.ToTable("operation_receipts", "learning");
                });

            modelBuilder.Entity("Sensei.Modules.Learning.Domain.RoadmapEnrollment", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid?>("CurrentStageId")
                        .HasColumnType("uuid")
                        .HasColumnName("current_stage_id");

                    b.Property<Guid>("OwnerId")
                        .HasColumnType("uuid")
                        .HasColumnName("owner_id");

                    b.Property<bool>("Paused")
                        .HasColumnType("boolean")
                        .HasColumnName("paused");

                    b.Property<Guid>("RoadmapVersionId")
                        .HasColumnType("uuid")
                        .HasColumnName("roadmap_version_id");

                    b.Property<int>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("integer")
                        .HasColumnName("version");

                    b.HasKey("Id");

                    b.HasIndex("CurrentStageId");

                    b.HasIndex("RoadmapVersionId");

                    b.HasIndex("OwnerId", "RoadmapVersionId")
                        .IsUnique();

                    b.ToTable("roadmap_enrollments", "learning");
                });

            modelBuilder.Entity("Sensei.Modules.Learning.Domain.RoadmapStage", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("ConceptId")
                        .HasColumnType("uuid")
                        .HasColumnName("concept_id");

                    b.Property<double>("MinimumCorrectness")
                        .HasColumnType("double precision")
                        .HasColumnName("minimum_correctness");

                    b.Property<int>("MinimumFamilies")
                        .HasColumnType("integer")
                        .HasColumnName("minimum_families");

                    b.Property<int>("MinimumSessions")
                        .HasColumnType("integer")
                        .HasColumnName("minimum_sessions");

                    b.Property<int>("Position")
                        .HasColumnType("integer")
                        .HasColumnName("position");

                    b.Property<Guid>("RoadmapVersionId")
                        .HasColumnType("uuid")
                        .HasColumnName("roadmap_version_id");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("title");

                    b.HasKey("Id");

                    b.HasIndex("ConceptId");

                    b.HasIndex("RoadmapVersionId", "Position")
                        .IsUnique();

                    b.ToTable("roadmap_stages", "learning");
                });

            modelBuilder.Entity("Sensei.Modules.Learning.Domain.RoadmapVersion", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<bool>("Available")
                        .HasColumnType("boolean")
                        .HasColumnName("available");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<string>("Locale")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("locale");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("title");

                    b.HasKey("Id");

                    b.ToTable("roadmap_versions", "learning");
                });

            modelBuilder.Entity("Sensei.Modules.Learning.Domain.SessionItem", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("DraftJson")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("draft_json");

                    b.Property<Guid>("ExerciseVersionId")
                        .HasColumnType("uuid")
                        .HasColumnName("exercise_version_id");

                    b.Property<bool>("HintUsed")
                        .HasColumnType("boolean")
                        .HasColumnName("hint_used");

                    b.Property<string>("Note")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("note");

                    b.Property<string>("Outcome")
                        .HasColumnType("text")
                        .HasColumnName("outcome");

                    b.Property<Guid>("OwnerId")
                        .HasColumnType("uuid")
                        .HasColumnName("owner_id");

                    b.Property<int>("Position")
                        .HasColumnType("integer")
                        .HasColumnName("position");

                    b.Property<bool>("ReferenceUsed")
                        .HasColumnType("boolean")
                        .HasColumnName("reference_used");

                    b.Property<bool>("Revealed")
                        .HasColumnType("boolean")
                        .HasColumnName("revealed");

                    b.Property<Guid>("SessionId")
                        .HasColumnType("uuid")
                        .HasColumnName("session_id");

                    b.HasKey("Id");

                    b.HasIndex("ExerciseVersionId");

                    b.HasIndex("SessionId", "Position")
                        .IsUnique();

                    b.ToTable("session_items", "learning");
                });

            modelBuilder.Entity("Sensei.Modules.Learning.Domain.StageTraversal", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("EnrollmentId")
                        .HasColumnType("uuid")
                        .HasColumnName("enrollment_id");

                    b.Property<Guid>("StageId")
                        .HasColumnType("uuid")
                        .HasColumnName("stage_id");

                    b.Property<string>("State")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("state");

                    b.HasKey("Id");

                    b.HasIndex("StageId");

                    b.HasIndex("EnrollmentId", "StageId")
                        .IsUnique();

                    b.ToTable("stage_traversals", "learning");
                });

            modelBuilder.Entity("Sensei.Modules.WorkReflection.Domain.WorkEpisode", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateOnly>("EventDate")
                        .HasColumnType("date")
                        .HasColumnName("event_date");

                    b.Property<bool>("IsArchived")
                        .HasColumnType("boolean")
                        .HasColumnName("is_archived");

                    b.Property<Guid>("OwnerId")
                        .HasColumnType("uuid")
                        .HasColumnName("owner_id");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(240)
                        .HasColumnType("character varying(240)")
                        .HasColumnName("role");

                    b.Property<string>("Setting")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("setting");

                    b.Property<string>("Summary")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("summary");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(240)
                        .HasColumnType("character varying(240)")
                        .HasColumnName("title");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<int>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("integer")
                        .HasColumnName("version");

                    b.HasKey("Id")
                        .HasName("pk_work_episodes");

                    b.HasIndex("OwnerId", "Id")
                        .IsUnique()
                        .HasDatabaseName("ux_work_episodes_owner_id");

                    b.HasIndex("OwnerId", "EventDate", "Id")
                        .HasDatabaseName("ix_work_episodes_owner_event_id");

                    b.ToTable("work_episodes", "work_reflection", t =>
                        {
                            t.HasCheckConstraint("ck_work_episodes_id_not_empty", "id <> '00000000-0000-0000-0000-000000000000'::uuid");

                            t.HasCheckConstraint("ck_work_episodes_owner_not_empty", "owner_id <> '00000000-0000-0000-0000-000000000000'::uuid");

                            t.HasCheckConstraint("ck_work_episodes_setting", "setting IN ('Employment', 'Coursework', 'PersonalProject', 'Other')");

                            t.HasCheckConstraint("ck_work_episodes_version_positive", "version >= 1");
                        });
                });

            modelBuilder.Entity("Sensei.Modules.Evidence.Domain.EvidenceObservation", b =>
                {
                    b.HasOne("Sensei.Modules.Learning.Domain.Concept", null)
                        .WithMany()
                        .HasForeignKey("ConceptId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_observations_concept");

                    b.HasOne("Sensei.Modules.Identity.Domain.UserAccount", null)
                        .WithMany()
                        .HasForeignKey("OwnerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_observations_owner");
                });

            modelBuilder.Entity("Sensei.Modules.Evidence.Domain.EvidenceStatusRevision", b =>
                {
                    b.HasOne("Sensei.Modules.Evidence.Domain.EvidenceObservation", null)
                        .WithMany()
                        .HasForeignKey("ObservationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Sensei.Modules.Evidence.Domain.KnowledgeContribution", b =>
                {
                    b.HasOne("Sensei.Modules.Learning.Domain.Concept", null)
                        .WithMany()
                        .HasForeignKey("ConceptId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Sensei.Modules.Learning.Domain.ExerciseFamily", null)
                        .WithMany()
                        .HasForeignKey("FamilyId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Sensei.Modules.Evidence.Domain.EvidenceObservation", null)
                        .WithMany()
                        .HasForeignKey("ObservationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Sensei.Modules.Learning.Domain.LearningAttempt", null)
                        .WithMany()
                        .HasForeignKey("OwnerId", "AttemptId")
                        .HasPrincipalKey("OwnerId", "Id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Sensei.Modules.Learning.Domain.ExerciseResult", null)
                        .WithMany()
                        .HasForeignKey("OwnerId", "ResultId")
                        .HasPrincipalKey("OwnerId", "Id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Sensei.Modules.Learning.Domain.LearningSession", null)
                        .WithMany()
                        .HasForeignKey("OwnerId", "SessionId")
                        .HasPrincipalKey("OwnerId", "Id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Sensei.Modules.Evidence.Domain.KnowledgeState", b =>
                {
                    b.HasOne("Sensei.Modules.Identity.Domain.UserAccount", null)
                        .WithMany()
                        .HasForeignKey("OwnerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Sensei.Modules.Evidence.Domain.SelfReviewAllowance", b =>
                {
                    b.HasOne("Sensei.Modules.Learning.Domain.Concept", null)
                        .WithMany()
                        .HasForeignKey("ConceptId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Sensei.Modules.Identity.Domain.UserAccount", null)
                        .WithMany()
                        .HasForeignKey("OwnerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Sensei.Modules.Experience.Domain.ExperienceEntry", b =>
                {
                    b.HasOne("Sensei.Modules.Identity.Domain.UserAccount", null)
                        .WithMany()
                        .HasForeignKey("OwnerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_entries_owner");
                });

            modelBuilder.Entity("Sensei.Modules.Experience.Domain.ExperienceRevision", b =>
                {
                    b.HasOne("Sensei.Modules.Experience.Domain.ExperienceEntry", null)
                        .WithMany("Revisions")
                        .HasForeignKey("EntryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Sensei.Modules.Experience.Domain.ExperienceRevisionConcept", b =>
                {
                    b.HasOne("Sensei.Modules.Learning.Domain.Concept", null)
                        .WithMany()
                        .HasForeignKey("ConceptId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_entry_revision_concepts_concept");

                    b.HasOne("Sensei.Modules.Experience.Domain.ExperienceRevision", null)
                        .WithMany("Concepts")
                        .HasForeignKey("EntryId", "RevisionNumber")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Sensei.Modules.Learning.Domain.ConceptRelation", b =>
                {
                    b.HasOne("Sensei.Modules.Learning.Domain.Concept", null)
                        .WithMany()
                        .HasForeignKey("SourceId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Sensei.Modules.Learning.Domain.Concept", null)
                        .WithMany()
                        .HasForeignKey("TargetId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Sensei.Modules.Learning.Domain.ExerciseConcept", b =>
                {
                    b.HasOne("Sensei.Modules.Learning.Domain.Concept", null)
                        .WithMany()
                        .HasForeignKey("ConceptId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Sensei.Modules.Learning.Domain.ExerciseVersion", null)
                        .WithMany()
                        .HasForeignKey("ExerciseVersionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Sensei.Modules.Learning.Domain.ExerciseResult", b =>
                {
                    b.HasOne("Sensei.Modules.Identity.Domain.UserAccount", null)
                        .WithMany()
                        .HasForeignKey("OwnerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Sensei.Modules.Learning.Domain.LearningAttempt", null)
                        .WithMany()
                        .HasForeignKey("OwnerId", "AttemptId")
                        .HasPrincipalKey("OwnerId", "Id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Sensei.Modules.Learning.Domain.ExerciseVersion", b =>
                {
                    b.HasOne("Sensei.Modules.Learning.Domain.ExerciseFamily", null)
                        .WithMany()
                        .HasForeignKey("FamilyId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Sensei.Modules.Learning.Domain.MaterialVersion", null)
                        .WithMany()
                        .HasForeignKey("MaterialVersionId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Sensei.Modules.Learning.Domain.Concept", null)
                        .WithMany()
                        .HasForeignKey("PrimaryConceptId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Sensei.Modules.Learning.Domain.GoalConcept", b =>
                {
                    b.HasOne("Sensei.Modules.Learning.Domain.Concept", null)
                        .WithMany()
                        .HasForeignKey("ConceptId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Sensei.Modules.Learning.Domain.LearningGoal", null)
                        .WithMany()
                        .HasForeignKey("GoalId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Sensei.Modules.Learning.Domain.LearningAttempt", b =>
                {
                    b.HasOne("Sensei.Modules.Identity.Domain.UserAccount", null)
                        .WithMany()
                        .HasForeignKey("OwnerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Sensei.Modules.Learning.Domain.LearningAttempt", null)
                        .WithMany()
                        .HasForeignKey("OwnerId", "PreviousAttemptId")
                        .HasPrincipalKey("OwnerId", "Id")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Sensei.Modules.Learning.Domain.SessionItem", null)
                        .WithMany()
                        .HasForeignKey("OwnerId", "SessionId", "ItemId", "ExerciseVersionId")
                        .HasPrincipalKey("OwnerId", "SessionId", "Id", "ExerciseVersionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Sensei.Modules.Learning.Domain.LearningEvent", b =>
                {
                    b.HasOne("Sensei.Modules.Learning.Domain.ExerciseVersion", null)
                        .WithMany()
                        .HasForeignKey("ExerciseVersionId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Sensei.Modules.Learning.Domain.MaterialVersion", null)
                        .WithMany()
                        .HasForeignKey("MaterialVersionId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Sensei.Modules.Identity.Domain.UserAccount", null)
                        .WithMany()
                        .HasForeignKey("OwnerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Sensei.Modules.Learning.Domain.LearningAttempt", null)
                        .WithMany()
                        .HasForeignKey("OwnerId", "AttemptId")
                        .HasPrincipalKey("OwnerId", "Id")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Sensei.Modules.Learning.Domain.LearningSession", null)
                        .WithMany()
                        .HasForeignKey("OwnerId", "SessionId")
                        .HasPrincipalKey("OwnerId", "Id")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("Sensei.Modules.Learning.Domain.LearningGoal", b =>
                {
                    b.HasOne("Sensei.Modules.Identity.Domain.UserAccount", null)
                        .WithMany()
                        .HasForeignKey("OwnerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Sensei.Modules.Learning.Domain.RoadmapVersion", null)
                        .WithMany()
                        .HasForeignKey("RoadmapVersionId")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("Sensei.Modules.Learning.Domain.LearningSession", b =>
                {
                    b.HasOne("Sensei.Modules.Learning.Domain.Concept", null)
                        .WithMany()
                        .HasForeignKey("ConceptId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Sensei.Modules.Identity.Domain.UserAccount", null)
                        .WithMany()
                        .HasForeignKey("OwnerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Sensei.Modules.Learning.Domain.RoadmapStage", null)
                        .WithMany()
                        .HasForeignKey("RoadmapStageId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Sensei.Modules.Learning.Domain.RoadmapEnrollment", null)
                        .WithMany()
                        .HasForeignKey("OwnerId", "EnrollmentId")
                        .HasPrincipalKey("OwnerId", "Id")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("Sensei.Modules.Learning.Domain.MaterialVersion", b =>
                {
                    b.HasOne("Sensei.Modules.Learning.Domain.Concept", null)
                        .WithMany()
                        .HasForeignKey("ConceptId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Sensei.Modules.Learning.Domain.OperationReceipt", b =>
                {
                    b.HasOne("Sensei.Modules.Identity.Domain.UserAccount", null)
                        .WithMany()
                        .HasForeignKey("OwnerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Sensei.Modules.Learning.Domain.RoadmapEnrollment", b =>
                {
                    b.HasOne("Sensei.Modules.Learning.Domain.RoadmapStage", null)
                        .WithMany()
                        .HasForeignKey("CurrentStageId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Sensei.Modules.Identity.Domain.UserAccount", null)
                        .WithMany()
                        .HasForeignKey("OwnerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Sensei.Modules.Learning.Domain.RoadmapVersion", null)
                        .WithMany()
                        .HasForeignKey("RoadmapVersionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Sensei.Modules.Learning.Domain.RoadmapStage", b =>
                {
                    b.HasOne("Sensei.Modules.Learning.Domain.Concept", null)
                        .WithMany()
                        .HasForeignKey("ConceptId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Sensei.Modules.Learning.Domain.RoadmapVersion", null)
                        .WithMany()
                        .HasForeignKey("RoadmapVersionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Sensei.Modules.Learning.Domain.SessionItem", b =>
                {
                    b.HasOne("Sensei.Modules.Learning.Domain.ExerciseVersion", null)
                        .WithMany()
                        .HasForeignKey("ExerciseVersionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Sensei.Modules.Identity.Domain.UserAccount", null)
                        .WithMany()
                        .HasForeignKey("OwnerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Sensei.Modules.Learning.Domain.LearningSession", null)
                        .WithMany()
                        .HasForeignKey("OwnerId", "SessionId")
                        .HasPrincipalKey("OwnerId", "Id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Sensei.Modules.Learning.Domain.StageTraversal", b =>
                {
                    b.HasOne("Sensei.Modules.Learning.Domain.RoadmapEnrollment", null)
                        .WithMany()
                        .HasForeignKey("EnrollmentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Sensei.Modules.Learning.Domain.RoadmapStage", null)
                        .WithMany()
                        .HasForeignKey("StageId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Sensei.Modules.WorkReflection.Domain.WorkEpisode", b =>
                {
                    b.HasOne("Sensei.Modules.Identity.Domain.UserAccount", null)
                        .WithMany()
                        .HasForeignKey("OwnerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_work_episodes_owner");
                });

            modelBuilder.Entity("Sensei.Modules.Experience.Domain.ExperienceEntry", b =>
                {
                    b.Navigation("Revisions");
                });

            modelBuilder.Entity("Sensei.Modules.Experience.Domain.ExperienceRevision", b =>
                {
                    b.Navigation("Concepts");
                });
#pragma warning restore 612, 618
        }
    }
}
