// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Sensei.BuildingBlocks.Persistence;

#nullable disable

namespace Sensei.Host.Persistence.Migrations
{
    [DbContext(typeof(SenseiDbContext))]
    [Migration("20260921172251_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.20")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Sensei.Modules.Evidence.Domain.EvidenceObservation", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Aspect")
                        .IsRequired()
                        .HasMaxLength(240)
                        .HasColumnType("character varying(240)")
                        .HasColumnName("aspect");

                    b.Property<string>("Assistance")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("assistance");

                    b.Property<Guid>("ConceptId")
                        .HasColumnType("uuid")
                        .HasColumnName("concept_id");

                    b.Property<string>("Conditions")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("conditions");

                    b.Property<DateTimeOffset>("ObservedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("observed_at");

                    b.Property<Guid>("OwnerId")
                        .HasColumnType("uuid")
                        .HasColumnName("owner_id");

                    b.Property<string>("SignalKind")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("signal_kind");

                    b.Property<Guid>("SourceId")
                        .HasColumnType("uuid")
                        .HasColumnName("source_id");

                    b.Property<string>("SourceKind")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("source_kind");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("status");

                    b.Property<int>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("integer")
                        .HasColumnName("version");

                    b.HasKey("Id")
                        .HasName("pk_observations");

                    b.HasIndex("ConceptId");

                    b.HasIndex("OwnerId", "ConceptId")
                        .HasDatabaseName("ix_observations_owner_concept");

                    b.HasIndex("OwnerId", "Id")
                        .IsUnique()
                        .HasDatabaseName("ux_observations_owner_id");

                    b.HasIndex("OwnerId", "ObservedAt", "Id")
                        .HasDatabaseName("ix_observations_owner_observed_id");

                    b.ToTable("observations", "evidence", t =>
                        {
                            t.HasCheckConstraint("ck_observations_id_not_empty", "id <> '00000000-0000-0000-0000-000000000000'::uuid");

                            t.HasCheckConstraint("ck_observations_owner_not_empty", "owner_id <> '00000000-0000-0000-0000-000000000000'::uuid");

                            t.HasCheckConstraint("ck_observations_version_positive", "version >= 1");
                        });
                });

            modelBuilder.Entity("Sensei.Modules.Experience.Domain.ExperienceEntry", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<bool>("IsArchived")
                        .HasColumnType("boolean")
                        .HasColumnName("is_archived");

                    b.Property<Guid>("OwnerId")
                        .HasColumnType("uuid")
                        .HasColumnName("owner_id");

                    b.Property<int>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("integer")
                        .HasColumnName("version");

                    b.HasKey("Id")
                        .HasName("pk_entries");

                    b.HasIndex("OwnerId", "Id")
                        .IsUnique()
                        .HasDatabaseName("ux_entries_owner_id");

                    b.HasIndex("OwnerId", "CreatedAt", "Id")
                        .HasDatabaseName("ix_entries_owner_created_id");

                    b.ToTable("entries", "experience", t =>
                        {
                            t.HasCheckConstraint("ck_entries_id_not_empty", "id <> '00000000-0000-0000-0000-000000000000'::uuid");

                            t.HasCheckConstraint("ck_entries_owner_not_empty", "owner_id <> '00000000-0000-0000-0000-000000000000'::uuid");

                            t.HasCheckConstraint("ck_entries_version_positive", "version >= 1");
                        });
                });

            modelBuilder.Entity("Sensei.Modules.Experience.Domain.ExperienceRevision", b =>
                {
                    b.Property<Guid>("EntryId")
                        .HasColumnType("uuid")
                        .HasColumnName("entry_id");

                    b.Property<int>("Number")
                        .HasColumnType("integer")
                        .HasColumnName("number");

                    b.Property<string>("Actions")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("actions");

                    b.Property<string>("Alternatives")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("alternatives");

                    b.Property<string>("ApprovalState")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("approval_state");

                    b.Property<DateTimeOffset?>("ApprovedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("approved_at");

                    b.Property<string>("Context")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("context");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("ImpactState")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("impact_state");

                    b.Property<string>("Outcome")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("outcome");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("role");

                    b.Property<string>("Setting")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("setting");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(240)
                        .HasColumnType("character varying(240)")
                        .HasColumnName("title");

                    b.HasKey("EntryId", "Number")
                        .HasName("pk_entry_revisions");

                    b.ToTable("entry_revisions", "experience", t =>
                        {
                            t.HasCheckConstraint("ck_entry_revisions_approval", "approval_state IN ('Draft', 'Approved', 'Retracted')");

                            t.HasCheckConstraint("ck_entry_revisions_impact", "impact_state IN ('Unknown', 'Qualitative', 'Measured')");

                            t.HasCheckConstraint("ck_entry_revisions_number_positive", "number >= 1");

                            t.HasCheckConstraint("ck_entry_revisions_setting", "setting IN ('Employment', 'Coursework', 'PersonalProject', 'Other')");
                        });
                });

            modelBuilder.Entity("Sensei.Modules.Experience.Domain.ExperienceRevisionConcept", b =>
                {
                    b.Property<Guid>("EntryId")
                        .HasColumnType("uuid")
                        .HasColumnName("entry_id");

                    b.Property<int>("RevisionNumber")
                        .HasColumnType("integer")
                        .HasColumnName("revision_number");

                    b.Property<Guid>("ConceptId")
                        .HasColumnType("uuid")
                        .HasColumnName("concept_id");

                    b.HasKey("EntryId", "RevisionNumber", "ConceptId")
                        .HasName("pk_entry_revision_concepts");

                    b.HasIndex("ConceptId")
                        .HasDatabaseName("ix_entry_revision_concepts_concept");

                    b.ToTable("entry_revision_concepts", "experience", t =>
                        {
                            t.HasCheckConstraint("ck_entry_revision_concepts_id_not_empty", "concept_id <> '00000000-0000-0000-0000-000000000000'::uuid");
                        });
                });

            modelBuilder.Entity("Sensei.Modules.Identity.Domain.UserAccount", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("AnswerLanguage")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("answer_language");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("display_name");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(320)
                        .HasColumnType("character varying(320)")
                        .HasColumnName("email");

                    b.Property<string>("TimeZone")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("time_zone");

                    b.Property<string>("UiLocale")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("ui_locale");

                    b.Property<int>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("integer")
                        .HasColumnName("version");

                    b.HasKey("Id")
                        .HasName("pk_users");

                    b.HasIndex("Email")
                        .IsUnique()
                        .HasDatabaseName("ux_users_email");

                    b.HasIndex("CreatedAt", "Id")
                        .HasDatabaseName("ix_users_created_at_id");

                    b.ToTable("users", "identity", t =>
                        {
                            t.HasCheckConstraint("ck_users_id_not_empty", "id <> '00000000-0000-0000-0000-000000000000'::uuid");

                            t.HasCheckConstraint("ck_users_version_positive", "version >= 1");
                        });
                });

            modelBuilder.Entity("Sensei.Modules.Learning.Domain.Concept", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<string>("Difficulty")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("difficulty");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("character varying(160)")
                        .HasColumnName("key");

                    b.Property<string>("Locale")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("locale");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(240)
                        .HasColumnType("character varying(240)")
                        .HasColumnName("name");

                    b.Property<int>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("integer")
                        .HasColumnName("version");

                    b.HasKey("Id")
                        .HasName("pk_concepts");

                    b.HasIndex("Key")
                        .IsUnique()
                        .HasDatabaseName("ux_concepts_key");

                    b.HasIndex("Key", "Id")
                        .HasDatabaseName("ix_concepts_key_id");

                    b.ToTable("concepts", "learning", t =>
                        {
                            t.HasCheckConstraint("ck_concepts_difficulty", "difficulty IN ('Beginner', 'Intermediate', 'Advanced')");

                            t.HasCheckConstraint("ck_concepts_id_not_empty", "id <> '00000000-0000-0000-0000-000000000000'::uuid");

                            t.HasCheckConstraint("ck_concepts_version_positive", "version >= 1");
                        });
                });

            modelBuilder.Entity("Sensei.Modules.WorkReflection.Domain.WorkEpisode", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateOnly>("EventDate")
                        .HasColumnType("date")
                        .HasColumnName("event_date");

                    b.Property<bool>("IsArchived")
                        .HasColumnType("boolean")
                        .HasColumnName("is_archived");

                    b.Property<Guid>("OwnerId")
                        .HasColumnType("uuid")
                        .HasColumnName("owner_id");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(240)
                        .HasColumnType("character varying(240)")
                        .HasColumnName("role");

                    b.Property<string>("Setting")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("setting");

                    b.Property<string>("Summary")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("summary");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(240)
                        .HasColumnType("character varying(240)")
                        .HasColumnName("title");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<int>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("integer")
                        .HasColumnName("version");

                    b.HasKey("Id")
                        .HasName("pk_work_episodes");

                    b.HasIndex("OwnerId", "Id")
                        .IsUnique()
                        .HasDatabaseName("ux_work_episodes_owner_id");

                    b.HasIndex("OwnerId", "EventDate", "Id")
                        .HasDatabaseName("ix_work_episodes_owner_event_id");

                    b.ToTable("work_episodes", "work_reflection", t =>
                        {
                            t.HasCheckConstraint("ck_work_episodes_id_not_empty", "id <> '00000000-0000-0000-0000-000000000000'::uuid");

                            t.HasCheckConstraint("ck_work_episodes_owner_not_empty", "owner_id <> '00000000-0000-0000-0000-000000000000'::uuid");

                            t.HasCheckConstraint("ck_work_episodes_setting", "setting IN ('Employment', 'Coursework', 'PersonalProject', 'Other')");

                            t.HasCheckConstraint("ck_work_episodes_version_positive", "version >= 1");
                        });
                });

            modelBuilder.Entity("Sensei.Modules.Evidence.Domain.EvidenceObservation", b =>
                {
                    b.HasOne("Sensei.Modules.Learning.Domain.Concept", null)
                        .WithMany()
                        .HasForeignKey("ConceptId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_observations_concept");

                    b.HasOne("Sensei.Modules.Identity.Domain.UserAccount", null)
                        .WithMany()
                        .HasForeignKey("OwnerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_observations_owner");
                });

            modelBuilder.Entity("Sensei.Modules.Experience.Domain.ExperienceEntry", b =>
                {
                    b.HasOne("Sensei.Modules.Identity.Domain.UserAccount", null)
                        .WithMany()
                        .HasForeignKey("OwnerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_entries_owner");
                });

            modelBuilder.Entity("Sensei.Modules.Experience.Domain.ExperienceRevision", b =>
                {
                    b.HasOne("Sensei.Modules.Experience.Domain.ExperienceEntry", null)
                        .WithMany("Revisions")
                        .HasForeignKey("EntryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Sensei.Modules.Experience.Domain.ExperienceRevisionConcept", b =>
                {
                    b.HasOne("Sensei.Modules.Learning.Domain.Concept", null)
                        .WithMany()
                        .HasForeignKey("ConceptId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_entry_revision_concepts_concept");

                    b.HasOne("Sensei.Modules.Experience.Domain.ExperienceRevision", null)
                        .WithMany("Concepts")
                        .HasForeignKey("EntryId", "RevisionNumber")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Sensei.Modules.WorkReflection.Domain.WorkEpisode", b =>
                {
                    b.HasOne("Sensei.Modules.Identity.Domain.UserAccount", null)
                        .WithMany()
                        .HasForeignKey("OwnerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_work_episodes_owner");
                });

            modelBuilder.Entity("Sensei.Modules.Experience.Domain.ExperienceEntry", b =>
                {
                    b.Navigation("Revisions");
                });

            modelBuilder.Entity("Sensei.Modules.Experience.Domain.ExperienceRevision", b =>
                {
                    b.Navigation("Concepts");
                });
#pragma warning restore 612, 618
        }
    }
}
